AWSTemplateFormatVersion: 2010-09-09
Description: >-
  api-admin-login

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Module:
    Type: String
    Default: api-admin-login
  Project:
    Type: String
    Default: apr
  Env:
    Type: String
    Default: dev
  JwtSsmParameterName:
    Type: String
    Default: jwt-secret


Globals:
  Function:
    Runtime: nodejs20.x
    CodeUri: src/
    Handler: index.handler
    Timeout: 30
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        PROJECT: !Ref Project
        ENV: !Ref Env
        USER_TABLE: !Ref UserTable

Resources:

# API Gateway Setup
  AdminLoginApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Description: API supporting admin functionalities.
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT'"
        AllowOrigin: "'*'"


# Lambda function config associated with the source code: health-check.js
  HealthCheck:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HealthCheck
      Description: GET method to get the health status of the api.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the UserTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref AdminLoginApi
            Path: /health
            Method: GET

  # This is a Lambda function config associated with the source code: get-all-items.js
  RegisterUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RegisterUser
      Handler: src/handlers/health-check.HealthCheck
      Description: GET method to get the health status of the api.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the UserTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        RegisterUser:
          Type: Api
          Properties:
            RestApiId: !Ref AdminLoginApi
            Path: /register
            Method: POST

  

  # Database
  UserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub admin-user-table-${Env}-${Module}
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  AdminLoginApi:
    Description: API Gateway endpoint URL for ${Env} stage admin login 
    Value:
      Fn::Sub: https://${AdminLoginApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/
